@version = HTTP/1.1
@PORT = 3333

@admin = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjowLCJ1c2VybmFtZSI6IjE4MzQxYTA1MzdAZ21yaXQuZWR1LmluIiwiaWQiOiI2MjMyMTVlYTUzZWY1YTI3MTU4Njg5ZjgiLCJpYXQiOjE2NDk1NDA1NDMsImV4cCI6MTY0OTU0NDE0M30.HWf-XVIv70G9oTCelZWyVxF-ucZyf-lAX3utwnNtjUI


# # Admin Login
# POST http://127.0.0.1:{{PORT}}/api/admin/ {{version}}
# Content-Type: application/json

# {
#     "username": "18341A0537@gmrit.edu.in",
#     "password": "iamsuperadmin"
# }


# Get all Members
GET http://127.0.0.1:3333/api/members/ {{version}}
Authorization: {{admin}}